### ISSUE TITLE
Kids are tryna sell your FF4

### ISSUE THREAD

**Issue by invaded** [DeprecatedLuke/fireflyx#2]
Hello, fyi people are selling FireFly 4 (I am sure w/o letting you know) and many of them are getting scammed due to them not having kUtils. Are you planning on open sourcing some stuff from ngxdevelopment services?

Firefly4, nLoader, etc etc?

**Comment by DeprecatedLuke** [comment]
kUtils can be figured out easily and I left that to anyone trying to use this to figure it out. nLoader still remains to be the most secure way of selling plugins as it loads classes without references making them incredibly hard to put back together so I won't be sharing that since it's most likely worth a lot as it guarantees your plugin can't be stolen and of it was open source people would steal it. And people who can't do any research are not my problem and can get scammed for all I care.

**Comment by invaded** [comment]
You discord so we can have a discussion about nLoader?

**Comment by DeprecatedLuke** [comment]
Not interested.
